#! /bin/sh

xrandr --output HDMI-0 --mode 2560x1440 --rate 144 --pos 0x240
xrandr --output DP-0 --mode 1920x1080 --rate 144 --pos 2560x0 --rotate right
# main monitor again because otherwise it's not positioned correctly
xrandr --output HDMI-0 --mode 2560x1440 --rate 144 --pos 0x240

xset s off -dpms
xset s noblank

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

export XDG_CURRENT_DESKTOP=kde

#export $(dbus-launch)

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config normal_border_color	 "#1e1e2e"
bspc config focused_border_color "#f38ba8"
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config pointer_motion_interval 7ms

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating
bspc rule -a discord desktop='^6'
bspc rule -a Spotify desktop='^6'
bspc rule -a Pavucontrol state=floating

/usr/lib/polkit-kde-authentication-agent-1 &

xsetroot -cursor_name left_ptr

polybar -r main &
polybar -r second &

picom --daemon &

#shuf -e -n 1 $HOME/.wallpapers/Custom/* | xargs feh --no-fehbg --bg-fill &
feh --no-fehbg --bg-fill $HOME/.wallpapers/Custom/colorful-mountains-night-minimal.jpg 

dunst &

redshift &

gwe --hide-window &

pulseeffects --gapplication-service &

#xfce4-power-manager &

/usr/lib/kdeconnectd &

deej -c /home/mateusz/.config/deej/config.yaml &

playerctld &

xidlehook --not-when-audio --not-when-fullscreen --timer 600 'betterlockscreen -l' '' --timer 300 'systemctl suspend' '' &

discord --start-minimized &
